[package]
name = "salsa"
version = "0.2.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nikomatsakis/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"
readme = "README.md"

[dependencies]
derive-new = "0.5.5"
rustc-hash = "1.0"
parking_lot = "0.6.4"
indexmap = "1.0.1"
log = "0.4.5"

[dev-dependencies]
difference = "2.0"
env_logger = "0.5.13"