[package]
name = "salsa"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/nikomatsakis/salsa"
description = "A generic framework for on-demand, incrementalized computation"
readme = "README.md"

[dependencies]
derive-new = "0.5.5"
rustc-hash = "1.0"
parking_lot = "0.6.4"